### ISSUE TITLE
containers - issue with prod / stack axis

### ISSUE THREAD

**Issue by cahofer** [radiocosmology/draco#14]
I pulled the most recent version of draco which I haven't done in a a few months (includes most recent pull request #13 ) and there seems to be some issue with the new SiderealStream container when I try to simulate a sidereal stream:

When using `draco/synthesis.stream.SimulateSidereal(task.SingleTask)`

`sstream = containers.SiderealStream(freq=freqmap, ra=ntime, input=feed_index,
                                            prod=tel.uniquepairs, distributed=True, comm=map_.comm)`

`  File "/project/6003614/cahofer/ch_pipeline/venv/src/draco/draco/core/containers.py", line 571, in __init__`
`    stack['prod'][:] = np.arange(len(prod))`
`ValueError: could not broadcast input array from shape (752) into shape (752,2)`

Is stack a 752, 2 array? 

Seems like this is already a quite old change (4 months ago by tristan)

**Comment by tristpinsm** [comment]
The line raising this error occurs because the stack is being constructed based on `np.empty_like(prod, dtype=[('prod', '<u4'), ('conjugate', 'u1')])`, when really what it should be using is `prod.shape[0]` or something. In the archive format, the `prod` index_map has shape `(nprod,)` and dtype `[('input_a', int), ('input_b', int)]`, but it seems this is not the case in the pipeline.

**Comment by cahofer** [comment]
To fit the simulations with the archive format I could do in simulate sidereal

`prod = np.zeros(tel.uniquepairs.shape[0], dtype=[('input_a', int), ('input_b', int)])`
`prod['input_a'] = tel.uniquepairs[:, 0]`
`prod['input_b'] = tel.uniquepairs[:, 1]`

correct?

**Comment by tristpinsm** [comment]
I think right now we should change that line (`containers.py:570) to `np.empty(prod.shape[0], dtype=[('prod', '<u4'), ('conjugate', 'u1')])`. But I was wondering if we want to continue with this different prod axis going forward.

**Comment by cahofer** [comment]
resolved
