### ISSUE TITLE
TypeError: process() missing 1 required positional argument: 'inp'`

### ISSUE THREAD

**Issue by Saraaqzs** [radiocosmology/draco#169]
Hi all,

I am trying to implement a pipeline for measuring power spectrum via draco (Or more specifically [the tools for 
Radio Cosmology](https://github.com/radiocosmology)). I wrote a config file with the appropriate tasks but I get the error:

`WARNING:draco.synthesis.stream.SimulateSidereal:Use of `output_root` is deprecated.
Traceback (most recent call last):
  File "/cluster/home/bin/caput-pipeline", line 8, in <module>
    sys.exit(cli())
  File "/cluster/apps/nss/python/3.7.4/x86_64/lib64/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/cluster/apps/nss/python/3.7.4/x86_64/lib64/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/cluster/apps/nss/python/3.7.4/x86_64/lib64/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/cluster/apps/nss/python/3.7.4/x86_64/lib64/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/cluster/apps/nss/python/3.7.4/x86_64/lib64/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/cluster/home/lib64/python3.7/site-packages/caput/scripts/runner.py", line 161, in run
    P.run()
  File "/cluster/home/lib64/python3.7/site-packages/caput/pipeline.py", line 633, in run
    out = task._pipeline_next()
  File "/cluster/home/lib64/python3.7/site-packages/caput/pipeline.py", line 1085, in _pipeline_next
    out = self.next(*args)
  File "/cluster/home/lib64/python3.7/site-packages/draco/core/task.py", line 347, in next
    output = self.process(*input)
TypeError: process() missing 1 required positional argument: 'inp'`

I couldn't pinpoint the source of the error and was not sure if it's related to the config file I wrote. Can you please help me with this?

**Comment by jrs65** [comment]
Hi! Can you post your pipeline config file? It looks to me like things probably aren't connect properly in there. Usually that error message is saying that there isn't as many inputs being passed into the task as it requires.

**Comment by Saraaqzs** [comment]
Ah OK, sorry I couldn't distinguish the missing input(s). So here's my config file:

`pipeline:
    tasks:
         -   type:       draco.core.task.SetMPILogging

        -   type:       draco.core.io.LoadProductManager
            out:        bt
            params:
                product_directory: /cluster/MeerKAT_test

        -   type:       draco.core.io.LoadMaps
            out:        imap
            params:
               maps:
                 files:
                      - /cluster/home/emissionMap.hdf5

        -   type:       draco.synthesis.stream.SimulateSidereal
            requires:   bt
            in:         imap
            out:        sstream
            params:
                save:   Yes
                output_root: /cluster/home/vis_ps_

        -   type:       draco.analysis.transform.MModeTransform
            requires:   bt
            in:         sstream
            out:        mmodes
        -  type:        draco.analysis.fgfilter.SVDModeProject
           requires:          bt
           out:         svdm
           params:
             save:     Yes
             output_root: /cluster/home/svd_ps_
        -  type:        draco.analysis.fgfilter.KLModeProject
           requires:    bt
           in:          mmodes
           out:         klm
           params:
               klname:  dk_3thresh_fg_10thresh
               save:    Yes
               output_root: /cluster/home/kl_ps_
        -  type:        draco.analysis.powerspectrum.QuadraticPSEstimation
           requires:    bt
           in:          klm
           out:         ps
           params:
               pstype:  minimum_variance
               psname:  psmc_dk_3thresh_fg_10thresh_1threshold
               save:    Yes
               output_root: /cluster/home/ps_`

And especially I don't know if `psname` and `klname` has to be the name of the folders in which KL-modes and PS-prods are generated from `drift-makeproducts` step or something else.

**Comment by jrs65** [comment]
Thanks! Your config looks good, except that SVDModeProject is missing an input. It should probably get `in: mmodes`

**Comment by Saraaqzs** [comment]
Yes, thanks a lot for your help! It's fixed now. 

P.S As a side note I also had to change `draco.analysis.fgfilter.KLModeProject` block to

```
    -  type:        draco.analysis.fgfilter.KLModeProject
       requires:    bt
       in:          svdm
       out:         klm
       params:
           klname:  dk_3thresh_fg_10thresh
           save:    Yes
           output_root: /cluster/home/kl_ps_
```
