### ISSUE TITLE
Fixes for ThresholdVisWeight

### ISSUE THREAD

**Issue by jrs65** [radiocosmology/draco#184]
This task has a few issues that should be fixed up.

Overall the point of the task is two fold:

- Identify gaps in the regridded data that are undetermined because of RFI. These regions have very small weights (like ~1e-8), rather than zero weights, because of the way the regridder works.
- Identify regions on the edges of RFI generated gaps in the data where the regridder hasn't done a good job, and the data should not be trusted. These often have weights that are a reasonable fraction of the typical weight for data that is present (something like ~20%), but this isn't really a good estimate of their uncertainty.

Both of these regions should have their weights set to zero.

As implemented this task has several issues:

- The major issue with this task is that the flagging decisions end up being baseline dependent, but the problem that it's trying to solve (i.e. the regridding issues) is baseline independent. This causes problems downstream as we pretty much assume that all the flagging like this depends only on time/frequency sample, but not on the actual baseline etc.
- At high frequencies near the edge of the band the weights roll off where we lose sensitivity. The current way that the fractional thresholding is done can cause those frequencies to be flagged out, even when they're actually fine (it's just that even in the best case that frequency has lower sensitivity).
- The way the flagging is performed is within the task itself. But typically we have a pattern of a task that determines that the masking should be and then another task which applies it. If the masking becomes baseline independent, then it can be represented as a standard RFI mask container, and can be applied with the usual `ApplyRFIMask` task.

I think a reasonable path to achieve this is:
- Redistribute the data over frequencies.
- Aggregate along the weights along the baseline axis. A simple mean/median over this axis should suffice.
- Apply an absolute value cut to the aggregated weights to samples values lower than a configurable threshold.
- Take the mean/median in time for each frequency *after* the previous mask (i.e. you want for each frequency, the typical value of samples that survived the absolute value cut).
- Use this as the baseline for the relative weight cut, i.e. for each sample mask it out if it is less than some threshold * aggregate for the current frequency.
- Generate an RFI mask container based on this.

**Comment by ljgray** [comment]
Unless I'm missing/not understanding something, this won't work with the current/standard `RFIMask` container because the axes are different.

**Comment by ljgray** [comment]
Addressed in #185
