### ISSUE TITLE
`dataset_id` flag has unicode type but is not checked when saving

### ISSUE THREAD

**Issue by ljgray** [radiocosmology/draco#213]
`CollateProducts` introduces a numpy unicode type somewhere in the timestream file. This only causes an issue when the timestream is saved, as h5py does not handle numpy unicode. There is a method in `caput.memh5` designed to handle this, but it misses this somehow. Related issues tracked here: radiocosmology/caput#230

**Comment by ljgray** [comment]
This is accompanied by introduction of NaN values in `CollateProducts` which are likely associated with an overflow warning in numpy multiply

**Comment by ljgray** [comment]
This bug was also present in rev_05. All of the days affected are new to rev_05+, so we can't compare to rev_04. There was one change made to `CollateProducts` in rev_05, so this is likely where the issue was introduced

**Comment by jrs65** [comment]
Have you confirmed that it isn't just a problem when loading data into the `CHIMETimeStream` container and trying to write it out? In that case there's no actual connection to `CollateProducts` it's just that there's an issue in there which causes it to try and dump the `CHIMETimeStream` container. It's quite likely that the original data has string typed datasets that will give issues (such as the `index_map/input` dataset).

**Comment by ljgray** [comment]
Yes, I'm able to write out the timestream files up until `CollateProducts`, including the tstream that is an input to `CollateProducts`

**Comment by ljgray** [comment]
It seems like there are two issues here, the NaN values in CollateProducts (there aren't any in the tstream input) and the dataset types. I'm assuming that they're related but not sure how

**Comment by ljgray** [comment]
You are right that the `index_map/input` have <U32 data in the correlator_input, which may the source of the problem. But I'm unclear as to why that would be fine before `CollateProducts` and fail afterwards

**Comment by jrs65** [comment]
I would guess that the issue is the reverse_stack constructed in `CollateProducts` (which has unicode types) and will get inserted into the container. However, what's unclear to me is why the types of the datasets in the incoming container aren't unicode themselves?!

Did you say that it didn't help if `convert_dataset_strings` was set?

**Comment by ljgray** [comment]
`convert_dataset_strings` didn't seem to help the first time I tried it but I want to try it again to confirm.

The odd thing is that the incoming dataset *does* have unicode types (`index_map`, `input`), which I'm looking at in a notebook. But apparently these are handled fine and can be saved with no differences in the parameters passed when saving.

**Comment by ljgray** [comment]
> `convert_dataset_strings` didn't seem to help the first time I tried it but I want to try it again to confirm.
> 
> The odd thing is that the incoming dataset _does_ have unicode types (`index_map`, `input`), which I'm looking at in a notebook. But apparently these are handled fine and can be saved with no differences in the parameters passed when saving. So it's something in the construction in `CollateProducts`, with the only relevant line being L218 `input=self.telescope.input_index,`

As a follow-up, I've definitely confirmed that `convert_dataset_strings` doesn't seem to help, and it is set to True as a class attribute anyway in the container created in `CollateProducts`

**Comment by ljgray** [comment]
Removing `containers.copy_datasets_filter` seems to remove the issue. Also, timestream files without a `dataset_id` flag seem to work fine (not entirely sure why some don't have it), so I think it's related to that.

**Comment by ljgray** [comment]
`dataset_id` can probably be made into a non-distributed dataset, which would result in it being converted properly. It would have to be handled different when used then. Alternatively, `caput.memh5` could check/convert it when saving.
