### ISSUE TITLE
Migrate to NumPy 1.17

### ISSUE THREAD

**Issue by anjakefala** [radiocosmology/draco#56]
This ticket is to track the migrating of the code to NumPy 1.17.

In NumPy 1.17, `RandomGen` was integrated into NumPy.

The advantage of using `RandomGen` over Numpy's legacy random is mainly performance.

From @jrs65:

```
As @tristpinsm says the advantage is performance, and there are certain tasks (of which this will be one) where the speed of the RNG is the bottleneck. I introduced it for the delay power spectrum estimator (which in some sense internally does what your doing here hundreds of times), and it took it down from 40 mins per power spectrum to more like 10 mins.
```

However, the changes made to the NumPy API as part of this integration were substantial. A small excerpt:

```
So, seeding seems to work in different ways for the "legacy random" and the "new generators".

RandomState provides access to legacy random https://numpy.org/devdocs/reference/random/legacy.html. get_state/set_state/seed specifically work with the legacy randoms https://numpy.org/devdocs/reference/random/legacy.html?highlight=seed.

The new RandomGenerator works by initialising a generator with a seed https://numpy.org/devdocs/reference/random/generator.html#numpy.random.Generator. SeedSequence https://numpy.org/devdocs/reference/random/bit_generators/generated/numpy.random.SeedSequence.html#numpy.random.SeedSequence is the main class that determines the sequence of seeds.

So if we bump to NumPy 1.17, it will be a bit of a refactor, and the two random generators do not intersect with their seed states.
```

**Comment by anjakefala** [comment]
As part of the work for this ticket, from @jrs65:

```


Obviously there was discussion elsewhere about this one. I'm happy to switch back to numpy's own ones (in v 1.17) provided they are as quick. It seems like I've not been using the explicit parallel generation (and that is supported anyway), but I don't think the fastest bit generators made it into numpy. Maybe you could benchmark a few things to see how they compare:

    Old numpy standard_normal
    New numpy standard_normal
    RandomGen equivalent

```

**Comment by anjakefala** [comment]
Ran each 10 times. This is a basic benchmark, where each uses the default random generator algorithm. Units are in seconds.
For standard_normal, RandomGen seems to be faster. 

Old numpy standard_normal
Average: 3.1322392225265503
Standard deviation: 0.07296019570012563

New numpy standard_normal
Average: 0.9457953691482544
Standard deviation: 0.015390708578744467

RandomGen standard_normal
Average: 0.6384477615356445
Standard deviation: 0.003192279068623649

**Comment by jrs65** [comment]
Thanks @anjakefala ! I think the only thing that was holding us back previously was the fact that there was a slight performance regression, however, I think that's entirely down to numpy not including the default BitGenerator in randomgen and changing to a slightly slower one (with better statistical properties apparently). If I change to one of the alternatives that is available in numpy (SFC64) I can get performance than with randomgen, so I don't see any reason not to move now.

**Comment by jrs65** [comment]
I always had this thought in the back of my mind that there was a fatal flaw with `mpi_random_seed` and I finally remembered what it was! It's that unless you think carefully about how you use it, it will re-seed everytime it's called and thus generate the same set of numbers over and over again, e.g. in `GaussianNoiseDataset` if you do a run where you process multiple datasets, each call to `process` will generate the exact same set of numbers!

I need to think carefully about how to do this sensibly.

**Comment by jrs65** [comment]
I think this is all done now.
