### ISSUE TITLE
_pack_marray function from commit 1d4730 buggy

### ISSUE THREAD

**Issue by pboubel** [radiocosmology/draco#64]
here the traceback
`  File "/home/pboubel/code/draco/draco/analysis/transform.py", line 548, in process
    marray = _make_marray(sstream.vis[:], mmax)
  File "/home/pboubel/code/draco/draco/analysis/transform.py", line 568, in _make_marray
    marray = _pack_marray(mmodes, mmax)
  File "/home/pboubel/code/draco/draco/analysis/transform.py", line 593, in _pack_marray
    marray[:mlim+1, 0] = mmodes[:mlim+1] # Non-negative modes
ValueError: could not broadcast input array from shape (3,7155,4096) into shape (2049,3,7155)`

This worked before the latest changes.

**Comment by pboubel** [comment]
@jdmena @jrs65

**Comment by jrs65** [comment]
This is fixed in #62 . Sorry, I meant to click merge earlier today.
